### ISSUE TITLE
Copy-paste from clipboard is not working

### ISSUE THREAD

**Issue by lavanyabjb** [simon123h/latex-image-paste#7]
I am using Atom version 1.58.0.
I have first installed the atom-latex package to work with latex. And then I have installed the latex-image-paste package. As per the package's documentation, I tried to copy-paste an image from the clipboard. But ctrl+v does not result in any action. I have just started using latex, so any help fixing this issue is highly appreciated.

**Comment by simon123h** [comment]
Thank you for your interest in the package and the bug report!

I think I could reproduce your issue and fixed it with 5a059adcad509917df5bba789c4bf108d565f567.

(The issue was that this package would activate only when a file was recognized as a LaTeX file by the language-latex package. Since atom-latex brings its own language support, the package language-latex is not necessary. I have now tweaked this extension to work with the atom-latex grammar as well.)

Feel free to reopen the issue, when the problem persists after updating the extension to 0.5.1 in your editor.
